### ISSUE TITLE
... is not a LiteDB database (v2.0.0-rc2)

### ISSUE THREAD

**Issue by adenflorian** [falahati/LiteDBViewer#1]
Installed via Release "LiteDB Viewer v1.1 - Setup" setup.exe
Ran LiteDB Viewer
Selected my .db file (which was created using LiteDB v2.0.0-rc2)
Got an error box with message "... is not a LiteDB database"
Where ... is the path to my .db file

I'm assuming it has something to do with it db being created using v2.0.0-rc2.
Let me know if there is anything else I can do to help!

**Comment by falahati** [comment]
Yeah, that is the exact reason. This program uses the LiteDB nuget binaries and as v2.0 is still in RC they are not available through nuget. As result, this program does not support LiteDB v2.0.
However, I believe that you can manually add reference to LiteDB v2.0 binaries and re compile the code. 

I hope that he soon release the final version of v2.0, I will then upgrade to LiteDB v2.0 or create another branch for LiteDB v2.0 if it was not compatible with v1.x.

**Comment by ldubrois** [comment]
Hello @falahati,

Would love to use your app with LiteDB v2.
The LiteDB v2-rc2 is available on nuget via the pre-release channel.

Hope you will support this version soon.

**Comment by falahati** [comment]
Good point, I am going to create a branch exactly for v2.0 as it seems incompatible with v1.x databases. Meanwhile, can you provide a sample database created in v2.0? It would help a lot.

**Comment by falahati** [comment]
@ldubrois , @AdenFlorian 
Please consider using this version: https://github.com/falahati/LiteDBViewer/releases/tag/v2.0.0-rc2

And get back to me about any problem or suggestion. It can be used side by side of any LiteDB Viewer v1.x release.

**Comment by adenflorian** [comment]
@falahati It works, thanks!

**Comment by ldubrois** [comment]
Thanks. I just installed it and I can open a DB v2.

Please find attached a small v2 DB.
[lem.zip](https://github.com/falahati/LiteDBViewer/files/388067/lem.zip)
