### ISSUE TITLE
Unable to open database file created using LiteDB v3.0.0

### ISSUE THREAD

**Issue by spawluk** [falahati/LiteDBViewer#10]
![screen](https://cloud.githubusercontent.com/assets/3480057/22618017/8d70b4fc-ead2-11e6-8139-ed307bea9949.png)

**Comment by QJonny** [comment]
ping

**Comment by falahati** [comment]
I take a look into this, expect a new version for LiteDB3 as I like to keep versions separated between major releases,

**Comment by falahati** [comment]
Download from here:
https://github.com/falahati/LiteDBViewer/releases/tag/v3.0.1

And please report any bug or functionality issues

**Comment by QJonny** [comment]
nice, works like a charm :)
