### ISSUE TITLE
Interested to merge the work into ErikEJ/SqlCeToolbox?

### ISSUE THREAD

**Issue by xied75** [falahati/LiteDBViewer#11]
Hi there,

The SqlCeToolbox:
https://github.com/ErikEJ/SqlCeToolbox
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox

Is a VS extension that is very popular. It would be great if your viewer can function there too. I've raised an issue there and Erik is happy to accept PR.
https://github.com/ErikEJ/SqlCeToolbox/issues/289

**Comment by falahati** [comment]
Hi Xied75,
Please tell me how this improves the situation for both project from your point of view, as I see no reason to do so.

**Comment by xied75** [comment]
That tool is used by many VS users, means we will install it almost by default. LiteDB is on the up, if a tool we already have can easily open LiteDB file, it will help LiteDB adoption too. Your tool is great, I have it installed as well, but I guess people would want VS integration?

**Comment by falahati** [comment]
Well, the VS integration in SqlCeToolbox is far more than what LiteDBViewer does. And as features of LiteDBViewer is limited to only viewing LiteDB files, I personally believe that integrating it into the SqlCeToolbox is a lot of hard work, to gain little.

Sorry, but at this moment I am not going to merge it into the SqlCeToolbox.
