### ISSUE TITLE
litedbview 4.0.0   right menu in win7

### ISSUE THREAD

**Issue by Anda001** [falahati/LiteDBViewer#16]
clear system， never installed ，3.0 version，just  download and installed 4.0.0 version；
when use context right menu button,it can't open,and the app think it was in 3.0 version

**Comment by falahati** [comment]
Unless you specifically select the 4th version to open a file, a default double-click tries to open it in v3.0. I mentioned this behavior in the release description:

> At this moment, LiteDBViewerVersionSelector can't differentiate between LiteDB 3.x and LiteDB 4.x files. Please rename your file to .db4 if you want to open it directly with double-click.

Or change the program in charge of opening `.db` files by doing this:
![image](https://user-images.githubusercontent.com/2479372/33009305-b0853a10-cdeb-11e7-907f-6ad1fea88942.png)

The reason for this is that the file version between LiteDB v3 and v4 didn't change. So the right move is to make LiteDBViewer 4 to open both versions v4 and v3. However, LiteDB v4 is still in beta and for the software to act right we need to wait for the stable release.

**Comment by wuzhenda** [comment]
![contextmenu](https://user-images.githubusercontent.com/1329895/33059271-8aa41922-cece-11e7-8d3d-656d7b0b3c90.jpg)

**Comment by wuzhenda** [comment]
![2222](https://user-images.githubusercontent.com/1329895/33059351-d35e7162-cece-11e7-9888-0030ac28a494.png)
