### ISSUE TITLE
Decimal and accented text

### ISSUE THREAD

**Issue by pazicb** [falahati/LiteDBViewer#17]
Hello,
I use your great product and have encountered several problems:
1. The decimal type is displayed throughout the application as "$ numberDecimal": "545,900". Would be possible to display see only the number?
2. The accented text appears encoded in the Result. E.g. "Ob\u00e1lka C5 samolep\u00edc\u00ed 1000 ks/bal.". In View String it's okay.

Thank you

**Comment by falahati** [comment]
Thank you,

Proposed features are now included in the master branch.
