### ISSUE TITLE
What is the query syntax?

### ISSUE THREAD

**Issue by voxoid0** [falahati/LiteDBViewer#18]

**Comment by voxoid0** [comment]
Probably something like this https://github.com/mbdavid/LiteDB/wiki/Expressions , but I still haven't applied it successfully. E.g. what if I just want to list all records where field1='bla'?

**Comment by dmlittledm** [comment]
in my case this sample query works correctly:
db.Order.find Number>33280 and AuthType="None" limit 100

**Comment by falahati** [comment]
Hey

Please read this:
https://github.com/mbdavid/LiteDB/wiki/Shell
