### ISSUE TITLE
Viewer Documentation

### ISSUE THREAD

**Issue by JoshuaWegener** [falahati/LiteDBViewer#23]
There is no mention which kind of query language is usable with this viewer. 
Except for the default "limit x" there are no Query Statements documented.

I would really appreciate at least a link to a usable documentation.

**Comment by falahati** [comment]
Hey,
The query syntax is the same as the `LiteDB.Shell` and is not actually part of this project but rather the `LiteDB` library it-self. Read more here:

https://github.com/mbdavid/LiteDB/wiki/Shell#collections-commands
https://github.com/mbdavid/LiteDB/wiki/Expressions

**Comment by falahati** [comment]
To be clear the link I posted here is not a documentation of LiteDB shell commands. But it partially describes a part of it. Shell commands also got a brief description here:
