### ISSUE TITLE
Database read error

### ISSUE THREAD

**Issue by MushrooM1337** [falahati/LiteDBViewer#26]
![image](https://user-images.githubusercontent.com/7921977/154441043-d648e268-c588-448d-be4c-e2a3daa1d9ac.png)

**Comment by falahati** [comment]
This tool has multiple versions that each match with a version of LiteDB used. If your database file is from version 5 or above, you have to use the official LiteDB Studio.

With the release of LiteDB Studio, as discussed in the readme file, this project won't continue with newer versions. V4 is the last version we are ever going to support.
