### ISSUE TITLE
LiteDB is not a database

### ISSUE THREAD

**Issue by saineshwar** [falahati/LiteDBViewer#4]
LiteDB is not a database when we select database it shows this error in windows pc
![capture](https://cloud.githubusercontent.com/assets/8281689/18025832/3aec3f92-6c53-11e6-9c69-af2d4b8da56b.JPG)

**Comment by falahati** [comment]
same as #3

**Comment by falahati** [comment]
Please consider testing https://github.com/falahati/LiteDBViewer/releases/tag/v2.0.1
