### ISSUE TITLE
Can't open db file

### ISSUE THREAD

**Issue by amgadfahmi** [falahati/LiteDBViewer#6]
Selected file is not a valid liteDB database file 
value can't be null 
parameter name:file name 

my db file name is IP.db and using latest version of ur app

**Comment by falahati** [comment]
Interesting. 
Did you try selecting the file using the open file dialog and without explorer? It seems that explorer for some wired reason don't pass the file address correctly.
Try opening the app directly from Start Menu and select your file, see what happens.

**Comment by amgadfahmi** [comment]
I did this and still getting same error

**Comment by falahati** [comment]
Where is your file? Full address please.

**Comment by amgadfahmi** [comment]
http://bit.ly/litedbtest

**Comment by falahati** [comment]
I just wanted the file address. not the file itself. And for the record file opens alright for me.

BUT,
This problem might be related to this issue:
https://github.com/mbdavid/LiteDB/issues/284

Which rooted in a bad piece of code that I contributed to the main project. So totally my fault. 
However, I can't fix it now by upgrading to version 2.0.2, as the program will lose its functionality about password protected files with certain characters. We all need to wait for the following pull request and 2.0.3 version of LiteDB (and LiteDBViewer).
https://github.com/mbdavid/LiteDB/pull/306

Meanwhile, you need to copy the file to an address without space in its name and see if this works for you.
Like your desktop or C:\ drive.

**Comment by amgadfahmi** [comment]
Yeah its working as the path had some spaces, would you make it clear for others until next version comes out. Thanks for the app

**Comment by tanwarsatya** [comment]
DB file is not opening I have tried all the options specified above, what's the next step. I am running the basic example mentioned on litedb website. Copied the file to C:\ as well ( MyData.db )

**Comment by falahati** [comment]
What is the exact error message and your database version? Can you attach it for me to test?

**Comment by tanwarsatya** [comment]
![capture](https://cloud.githubusercontent.com/assets/1289839/19011138/cd608f40-875b-11e6-98df-f6e1adb86452.PNG)

'MyData.db' is not a LiteDB database

**Comment by falahati** [comment]
This error code is generated directly by the LiteDB libraries so I cant do much about it. Probably something is wrong with the file.

**Comment by tanwarsatya** [comment]
I guess I found issue is simple, the setup available is referencing old LiteDB.dll. I will suggest to update the code to reference new dlls.

**Comment by falahati** [comment]
This could be an issue if you tried opening a Litedb 2 database using version 1 of LiteDB viewer. For this please download and install LiteDBViewer2: https://github.com/falahati/LiteDBViewer/releases/tag/v2.0.1
Also if you have both versions 1 and 2, you need to use OpenWith command and select the correct version of LiteDBViewer for your database file.
