### ISSUE TITLE
Enable deleting a row,  editing a cell value

### ISSUE THREAD

**Issue by igorushi** [falahati/LiteDBViewer#7]
Could you please add those?

**Comment by falahati** [comment]
Hey Igor,

As the name of the project clearly shows, this project was only meant for viewing and extracting data from a LiteDB database and not altering it. So at the moment I have no intention to expand the project and add these features to it. 

However, I leave this issue open so others can comment and show their interest in this feature.

Thanks for contacting

**Comment by bryanhitc** [comment]
I'd absolutely love to be able to edit cell values, and it would be even more nice if there was functionality to add/remove rows.

**Comment by falahati** [comment]
Btw, you can always do these using the text box at the top of the form. It is similar to the LiteDB.Shell command line.

**Comment by JosefNemec** [comment]
Hi, since author of this project doesn't plan to add editing features I decided to write my own editor. You can check it here: https://github.com/JosefNemec/LiteDbExplorer

**Comment by falahati** [comment]
A very nice and elegant tool Josef, thank you for sharing that with us.

Now with a tool like that already out there, I believe that this issue is already resolved.

Thanks all for showing their interest in the proposed feature.

**Comment by falahati** [comment]
Project added to the readme file
