### ISSUE TITLE
Unable to Open DB

### ISSUE THREAD

**Issue by varshanbp** [falahati/LiteDBViewer#9]
I get error even if I select Valid LiteDB file. This happens in v2.0.1 (Windows).

Selected file is not valid LiteDB Database file.
Value cannot be null.
Parameter name: filename

**Comment by falahati** [comment]
This is a known issue of the LiteDB library used with this project. You need to move your file to an address without space in it.

I will release a new version of this project with the updated LiteDB library shortly.

**Comment by falahati** [comment]
This will be solved if using the latest release for LiteDB 2.0, LiteDBViewer 2.0.4
